# Generated by Django 3.2 on 2024-06-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20240624_1804'),
        ('reviews', '0006_auto_20240624_2140'),
    ]

    operations = [
    ]
