# Generated by Django 3.2 on 2024-06-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_merge_0006_auto_20240624_1804_0006_auto_20240624_2140'),
        ('reviews', '0010_alter_title_options'),
    ]

    operations = [
    ]
